SENSOR_BH1750_VERSION = main
SENSOR_BH1750_SITE = https://github.com/LeonardoSanBenitez/sensor_bh1750_linux_driver
SENSOR_BH1750_SITE_METHOD = git


SENSOR_BH1750_LICENSE = GPLv2
SENSOR_BH1750_LICENSE_FILES = COPYING

define KERNEL_MODULE_BUILD_CMDS
$(MAKE) -C '$(@D)' LINUX_DIR='$(LINUX_DIR)' CC='$(TARGET_CC)' LD='$(TARGET_LD)' modules
endef

define SENSOR_BH1750_INSTALL_INIT_SCRIPT
        $(INSTALL) -D -m 0755 $(SENSOR_BH1750_PKGDIR)/S70sensor_bh1750 $(TARGET_DIR)/etc/init.d/
endef
SENSOR_BH1750_POST_INSTALL_TARGET_HOOKS += SENSOR_BH1750_INSTALL_INIT_SCRIPT

$(eval $(kernel-module))
$(eval $(generic-package))

